/**
 * aiAnalyzer.js
 * ---------------------------------------------------------------------------
 * AI-powered recommendation generator for SiteFix AI, backed by the Claude
 * API. It only ever runs server-side — the API key never reaches the
 * browser (see server/services/ai/claudeClient.js, the shared low-level
 * caller used by this file and fixGenerator.js).
 *
 * generateRecommendations(scanResult, auditResult):
 *   1. Extracts a small, bounded set of real facts from the scan + audit
 *      data (server/services/ai/promptBuilder.js) — nothing else is sent.
 *   2. Calls Claude with a strict prompt: only reason from the supplied
 *      facts, never invent data about this website, never guarantee
 *      rankings/traffic/conversions, respond with JSON only.
 *   3. Parses and validates the JSON response
 *      (server/services/ai/responseValidator.js) — malformed or unsafe
 *      output is filtered out rather than passed through.
 *
 * Configuration (see .env.example):
 *   ANTHROPIC_API_KEY    required — no default, no fallback key.
 *   ANTHROPIC_MODEL      optional — defaults to a current Claude model.
 *   ANTHROPIC_MAX_TOKENS optional — defaults to 4096.
 * ---------------------------------------------------------------------------
 */

const { callClaude } = require('./ai/claudeClient');
const { extractFacts, buildPrompt } = require('./ai/promptBuilder');
const { parseAndValidate } = require('./ai/responseValidator');
const { AINotReadyError } = require('./ai/errors');
const errors = require('./ai/errors');

const MAX_FACTS_JSON_CHARS = 12000; // reasonable input-size cap before sending to Claude

/**
 * Progressively trims the facts payload if it's larger than reasonable,
 * rather than sending an unbounded amount of data (and paying for it) on
 * pages with unusually large findings lists.
 */
function enforceInputSizeLimit(facts) {
  let candidate = facts;
  if (JSON.stringify(candidate).length <= MAX_FACTS_JSON_CHARS) return candidate;

  // Tier 1: drop the lowest-priority ('info') findings first.
  candidate = { ...candidate, findings: candidate.findings.filter((f) => f.severity !== 'info') };
  if (JSON.stringify(candidate).length <= MAX_FACTS_JSON_CHARS) return candidate;

  // Tier 2: hard-cap remaining findings.
  candidate = { ...candidate, findings: candidate.findings.slice(0, 15) };
  return candidate;
}

/**
 * Generate AI-powered recommendations from a completed scan + audit.
 *
 * @param {object} scanResult  ScanResult from websiteScanner.scanWebsite().
 * @param {object} auditResult AuditResult from auditEngine.runAudit().
 * @returns {Promise<object>} The full analysis envelope (see below).
 * @throws {import('./ai/errors').AIError}
 */
async function generateRecommendations(scanResult, auditResult) {
  if (!scanResult || !auditResult) {
    throw new AINotReadyError();
  }

  const rawFacts = extractFacts(scanResult, auditResult);
  const facts = enforceInputSizeLimit(rawFacts);
  const { system, user } = buildPrompt(facts);

  const { text, model } = await callClaude({ system, user });
  const validated = parseAndValidate(text, facts);

  return {
    generatedAt: new Date().toISOString(),
    model,
    // Deterministic facts this analysis was grounded in -- kept clearly
    // separate from the AI-generated fields below.
    basedOn: {
      overallScore: facts.overallScore,
      categoryScores: facts.categoryScores,
      totalChecks: facts.totalChecks,
      checksPassed: facts.checksPassed,
      findingsAnalyzed: facts.findings.length,
    },
    // Everything from here down is AI-generated.
    executiveSummary: validated.executiveSummary,
    recommendations: validated.recommendations,
    topImprovements: validated.topImprovements,
    quickWins: validated.quickWins,
    longTermImprovements: validated.longTermImprovements,
    disclaimer:
      'These recommendations are generated by AI based on the detected data above. ' +
      'They are suggestions, not guarantees of search ranking, traffic, or conversion improvements.',
  };
}

module.exports = {
  generateRecommendations,
  errors,
};
